### ISSUE TITLE
Normalized email address issue

### ISSUE THREAD

**Issue by Urogna** [hoangvvo/nextjs-mongodb-app#105]
I believe users whose email address has been altered because of normalization can't be found in the database, thus preventing them from logging in. (email is normalized on signup, but not on login)

**Comment by hoangvvo** [comment]
> I believe users whose email address has been altered because of normalization can't be found in the database, thus preventing them from logging in. (email is normalized on signup, but not on login)

Thanks for the issue. Would you like to make a PR?
