### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by ghost** [hoangvvo/nextjs-mongodb-app#110]
Hello, why posts opens so slow? It should work much faster

**Comment by haggistech** [comment]
slow all the time? Are you using this one or your own one?

**Comment by hoangvvo** [comment]
For future readers, the speed should depend on the database hosting. In this case, I'm using a free-tier database so it is obviously not so good. 

In addition, in serverless, the database connection is not always persisted, so for some requests there is a short period of wait time for the connection to be established.
