### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by MohammedADev** [hoangvvo/nextjs-mongodb-app#114]
**Describe the bug**
When going to your profile to verify your email you get "Bad Request"
**To Reproduce**
1.Sign in
2. Edit Profile
3. Send verification email (gets error)

**Expected behavior**
To send a verification email

**Screenshots**
https://prnt.sc/za0za6

**Desktop (please complete the following information):**
 - Desktop
 - Chrome
 - idk

**Comment by hoangvvo** [comment]
This error is caused because my SendGrid account was removed a while ago. It should work if you use your own SendGrid API Key

**Comment by MohammedADev** [comment]
Oh ok
