### ISSUE TITLE
Question: What is the difference between just return the connection and pass it on middleware?

### ISSUE THREAD

**Issue by riflowth** [hoangvvo/nextjs-mongodb-app#120]
What benefits of making MongoDB middleware?

If I can do that
e.g. *(pseudo-code)*
```js

let client

export default async function db() {
  if (!client) {
    client = new MongoClient(.....................)
    await client.connect()
  }
  
  return client
}
```
more example that looks like the code above: 
https://developer.mongodb.com/how-to/nextjs-with-mongodb/#example-1--next.js-api-endpoint-with-mongodb

> Usage: Just require and then call db().collection................. for working with the database

and

https://github.com/hoangvvo/nextjs-mongodb-app/blob/master/middlewares/database.js#L23-L34

**Comment by hoangvvo** [comment]
This is just a pattern this project is using. There should not be any difference between the two methods.

**Comment by riflowth** [comment]
Thanks for replying to me so this ticket should be closed.
