### ISSUE TITLE
Trying to signup but getting an error "cannot read property 0 of undefined"

### ISSUE THREAD

**Issue by rawjson** [hoangvvo/nextjs-mongodb-app#126]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hoangvvo** [comment]
@navdesign  Can you try again? I just published a fix for that issue. Thank you!

**Comment by rawjson** [comment]
Thank you! the app is working as expected. However, i am having an issue with my set up. When i tried running your setup, i got the same issue. 

this is what is get: ----

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined

I dont understand where this issue is coming from and why. 

The end of the line in the console prints API resolved without sending a response request at api/user

can you help me out???


this is the whole error that is printed in the console {
error - unhandledRejection: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
    at Function.byteLength (buffer.js:727:11)
    at ServerResponse.apiRes.end (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\next\dist\server\api-utils.js:72:41)     
    at writeend (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\express-session\index.js:262:22)
    at ontouch (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\express-session\index.js:353:11)
    at C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\connect-mongo\build\main\lib\MongoStore.js:334:24
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
    at Function.byteLength (buffer.js:727:11)
    at ServerResponse.apiRes.end (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\next\dist\server\api-utils.js:72:41)     
    at writeend (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\express-session\index.js:262:22)
    at ontouch (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\express-session\index.js:353:11)
    at C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\connect-mongo\build\main\lib\MongoStore.js:330:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

}

**Comment by hoangvvo** [comment]
> Thank you! the app is working as expected. However, i am having an issue with my set up. When i tried running your setup, i got the same issue. 
> 
> this is what is get: ----
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
> 
> I dont understand where this issue is coming from and why. 
> 
> The end of the line in the console prints API resolved without sending a response request at api/user
> 
> can you help me out???
> 
> 
> this is the whole error that is printed in the console {
> error - unhandledRejection: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
>     at Function.byteLength (buffer.js:727:11)
>     at ServerResponse.apiRes.end (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\next\dist\server\api-utils.js:72:41)     
>     at writeend (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\express-session\index.js:262:22)
>     at ontouch (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\express-session\index.js:353:11)
>     at C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\connect-mongo\build\main\lib\MongoStore.js:334:24
>     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
>   code: 'ERR_INVALID_ARG_TYPE'
> }
> TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
>     at Function.byteLength (buffer.js:727:11)
>     at ServerResponse.apiRes.end (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\next\dist\server\api-utils.js:72:41)     
>     at writeend (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\express-session\index.js:262:22)
>     at ontouch (C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\express-session\index.js:353:11)
>     at C:\Users\Dell\Documents\GitHub\lawopt-nextjs\node_modules\connect-mongo\build\main\lib\MongoStore.js:330:28
>     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
>   code: 'ERR_INVALID_ARG_TYPE'
> }
> 
> }

There is an issue when using express-session with Next.js 11. I replaced it in the latest commits, so try pulling new code.

**Comment by hoangvvo** [comment]
I cannot reproduce this. Please reopen if it still happens
