### ISSUE TITLE
req.logIn NOT FUNCTION

### ISSUE THREAD

**Issue by hthrkuh** [hoangvvo/nextjs-mongodb-app#136]
**Describe the bug**
nextjs-mongodb-app/pages/api/users/index.js 

the " ...auths" is missing 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hoangvvo** [comment]
Thanks, would you like to make a PR?

**Comment by hoangvvo** [comment]
Thanks for reporting. Fixed in 0496af33a39bcbddc9f5604cf221a7789c0f220b
