### ISSUE TITLE
[RFC] Rewrite with next-connect

### ISSUE THREAD

**Issue by hoangvvo** [hoangvvo/nextjs-mongodb-app#17]
Hi everyone,

I'm thinking of rewriting this project with my library [next-connect](https://www.npmjs.com/package/next-connect). It makes it easier to work with method routing and middleware.

At the moment, our middleware approach is to have wrapper function (like HOC) (See my [post](https://dev.to/hoangvvo/use-middlewares-in-next-js-without-custom-server-53i). I'm thinking of rewriting it with next-connect (info in the same post)

**Comment by hoangvvo** [comment]
method routing
```
// old
const handler = (req, res) => {
  if (req.method === 'POST') {
 ...
}
 if (req.method === 'PUT') {
...
 }
}
// new
handler.post((req, res) => { ... })
handler.put((req, res) => { ... })
```

middleware

```
// old
withThisMiddleware(withThatMiddleware(handler))
// new
handler.use(thisMiddleware())
handler.use(thatMiddleware())
```

**Comment by louisgv** [comment]
This will make it so much cleaner! Also in your blog, you mentioned that `next-connect` works with `passport`. Would love to play around with it sometime next week and make a PR after you migrated to `next-connect`!
