### ISSUE TITLE
sending form data with text and image to Api route

### ISSUE THREAD

**Issue by kumosal** [hoangvvo/nextjs-mongodb-app#18]
Hi, first of all, thanks for making this project.

In the settings.js page, I see two forms. One form to update text fields that can be parsed by default bodyParser, and another to upload an image to be processed by formidable. I wonder why you made this decision instead of making  one form. Isn't it possible to have just one form?
btw, I'm new to nextjs and its api routes.

**Comment by hoangvvo** [comment]
@kumosal Thanks for asking, **`bodyParser` does not play well with our Formidable parser**. Formidable supposed to parse the incoming request stream. However, the process is done by `bodyParser` before Formidable can jump in.

Also, even if the two plays well with each other, I still prefer to separate the two functionalities into two files to avoid the complexity of having them both in one.

**Comment by kumosal** [comment]
@hoangvvo In the case of a social site like this one, I think the functionality of submitting a post with image(s) would be a good feature. Do think Formidable can alone parse both text and image fields coming from one form?

**Comment by hoangvvo** [comment]
@kumosal I would not bet on it. The readme for Formidable does not mention anything about that. 
However, it may still be possible that it can do that. In `form.parse(req, (err, fields, files) => {})`, we have been using `files`. Try looking into `fields` to see if other fields are there. Either way, make sure to disable Next.js `bodyParser`.

However, on a side note, `Formidable` is not really maintained. If you find another library that does the same thing, please tell me or make a PR.

**Comment by hoangvvo** [comment]
#22 enables the usage of Connect/Express middleware. Therefore it is now possible to use [multer](https://github.com/expressjs/multer) for the job.

**Comment by hoangvvo** [comment]
@kumosal Implemented in #45 :tada:

**Comment by kumosal** [comment]
Well done!
