### ISSUE TITLE
Clarify usage with .env in documentation

### ISSUE THREAD

**Issue by ScorpIan555** [hoangvvo/nextjs-mongodb-app#2]
1)  Cloned app
2) 'npm i'
3) created .env file in app root directory
4) added local mongodb connection string

Hey, I am new to NextJS so was using your app & tutorial as a guide to getting mine up (liked your custom auth/session config as well).  In troubleshooting my own connection (I went a slightly different way with a few things), I cloned your app to have a look as a shortcut to testing my own connection & to have a point of reference...

I had to manually add in the connection strings.  I haven't had the chance to troubleshoot this just yet (and prob won't get to it right away) so I just wanted to let you know.

**Comment by hoangvvo** [comment]
Hey @Scorplan555, sorry I did not make this clearer.

In my [post](https://www.hoangvvo.com/blog/full-fledged-app-with-next-js-and-mongodb-part-1/#environmental-variables), I mention some method to use `.env`.

https://github.com/zeit/next.js/tree/canary/examples/with-dotenv

I will update the documentation to make this clearer.

Thanks.
