### ISSUE TITLE
FEAT | Swagger integration for open API 

### ISSUE THREAD

**Issue by louisgv** [hoangvvo/nextjs-mongodb-app#21]
Using https://www.npmjs.com/package/swagger-ui-react, it should be fairly trivial to add a swagger page that render the specs of certain api route.

**Comment by hoangvvo** [comment]
Hey @louisgv, this is a good idea. However, I would avoid adding additional dependency for this. Would it be possible without `swagger-ui-react`?

**Comment by hoangvvo** [comment]
Closing due to lack of interest...
