### ISSUE TITLE
api is not working

### ISSUE THREAD

**Issue by tufail** [hoangvvo/nextjs-mongodb-app#27]
https://nextjs-mongodb-app.hoangvvo.now.sh/signup

**Comment by hoangvvo** [comment]
hey @tufail, please update `next-connect` to the latest version to fix this issue. I'm updating the demo.

**Comment by hoangvvo** [comment]
@tufail The demo were also built without environment vairables, and I have resolve the issue. Also check out and pull the latest code, which I include a more detailed instruction on environment variables.
