### ISSUE TITLE
Feature-request: forgot password email.

### ISSUE THREAD

**Issue by dhacquebord** [hoangvvo/nextjs-mongodb-app#29]
I think it would be useful to add the possibility for the user to request a link to reset his/her password. Are you planning on implementing this in the near future or should i implement this myself via a PR?

**Comment by hoangvvo** [comment]
Hey @dhacquebord, thanks for your interest in submmiting a PR. I have already worked out this feature, sorry :p . I will land it this weekend. Just curious, what is your approach?

**Comment by dhacquebord** [comment]
Hi hoangvvo, Thank you for letting me know, saves me some time. 😁  I didn't really have an approach yet, i would've had to figure that out. I'm looking forward to seeing your solution!

**Comment by hoangvvo** [comment]
@dhacquebord landed in #35. It does not work on the demo. But should work if you use it with your own SendGrid API Key (or replace it with other providers) (#36 )
