### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [hoangvvo/nextjs-mongodb-app#30]
Hello, what if I wanted to make a query, from the API folder I could take the data to an application on flutter ?, That is, consume Flutter with the data used on the web (login)

Thank you very much, I hope your answer

**Comment by FranciscoImanolSuarez** [comment]
I think that my case could also be related to this "https://github.com/hoangvvo/nextjs-mongodb-app/issues/21", since with the swagger theme we could see the API routes and thus be able to access from the outside bone another app

**Comment by hoangvvo** [comment]
This is certainly possible. However, you will need to create your own authentication logic that allows the Flutter app to communicate with our API.

This is  related to #16.

**Comment by hoangvvo** [comment]
This requires Header bearer token authentication. Please track it in #33.
