### ISSUE TITLE
Sendgrid API and email-related features

### ISSUE THREAD

**Issue by hoangvvo** [hoangvvo/nextjs-mongodb-app#36]
The SendGrid account I use in `nextjs-mongodb-app` has been flagged, and I could not create a new one.

Therefore, the following features do not work:

- Email verification
- Password reset

Does anyone have a spare/unused/extra SendGrid account?

**Comment by MontoyaAndres** [comment]
Hey, I'm having some problems with sendgrid as well, I just need to send an email to a gmail account and that's it, but it does not work. This is the complete problem:

https://stackoverflow.com/questions/59638166/trying-to-send-email-with-sendgrid-to-an-gmail-email-but-i-get-a-pending-messa

Do you know how to resolve it? I saw that your implementation works well and I have the same here:

https://github.com/MontoyaAndres/carga-logistica/blob/master/pages/api/index.ts

But I don't know why I does not work :(

**Comment by hoangvvo** [comment]
@MontoyaAndres That's odd. Can you try `await` `sendGrid.send()` before `res.send`?

**Comment by brohlson** [comment]
Mailgun would be a suitable drop-in replacement:
https://www.mailgun.com/

Great free tier

**Comment by MontoyaAndres** [comment]
@hoangvvo that didn't work, @brohlson do you a little example?

**Comment by brohlson** [comment]
From a gatsby build:
https://github.com/brohlson/chaseohlson/blob/master/functions-src/contact.js

**Comment by MontoyaAndres** [comment]
@brohlson I'll give a try, maybe this tool can resolve the problem that @hoangvvo has :)
