### ISSUE TITLE
502 Error on Login

### ISSUE THREAD

**Issue by brohlson** [hoangvvo/nextjs-mongodb-app#40]
## Steps to reproduce
- Sign up 
- Log out 
- Sign in with new credentials 

Mac OSX - Latest Chrome 

![c6e64103-b0d9-4611-a049-436ac6a0f493](https://user-images.githubusercontent.com/18178678/72111121-c06a0400-32ee-11ea-8c77-db8b1eda14be.png)

**Comment by brohlson** [comment]
Seems like maybe just adding a try/catch block in the api file and returning a status should fix it.  The login actually seems to work when you get back to the app. 

https://github.com/hoangvvo/nextjs-mongodb-app/blob/master/pages/api/authenticate.js

**Comment by hoangvvo** [comment]
Fix in #43
