### ISSUE TITLE
Quill wysiwyg integration

### ISSUE THREAD

**Issue by JurajJakubov** [hoangvvo/nextjs-mongodb-app#44]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It will be nice to have integration with Quill. While image uploaded to quill will be uploaded directly to the project folder, not any online service.

**Describe alternatives you've considered**

**Additional context**
This feature needs more work to be implemented so I understand if it will be rejected.

**Comment by hoangvvo** [comment]
Hi @JurajJakubov, could you clarify what you mean by "directly to the project folder". Where would that be? It is not possible for us to store anything in serverless. We would need to spin up things such as Amazon S3.

**Comment by JurajJakubov** [comment]
Sorry I probably need to understand concept of serverless first 😅. Anyway some quill implementation will be nice.

**Comment by hoangvvo** [comment]
Hey, I am sorry to close this since I'm not intending on getting this in. The goal of this project is to keep it as simple and unopinionated as possible. Thus exttra libraries are to be avoided.

You can open a fork and I will try to help you implement it
