### ISSUE TITLE
createContext requires 1-2 arguments, cannot use without any arguments

### ISSUE THREAD

**Issue by maysam** [hoangvvo/nextjs-mongodb-app#48]
```const UserContext = createContext();```

in

https://github.com/hoangvvo/nextjs-mongodb-app/blob/master/components/UserContext.jsx#L4

requires 1-2 arguments, cannot use without any arguments

**Comment by hoangvvo** [comment]
Hey @maysam, `React.createContext()` only accepts one argument which is the default value, used when we have no provider.

However, we do have a provider that supplies the value, so we do not need it.

```
<UserContext.Provider value={{ state, dispatch: dispatchProxy }}>
      {children}
    </UserContext.Provider>
```

https://reactjs.org/docs/context.html#reactcreatecontext

**Comment by maysam** [comment]
This is the error I am getting

```
42:22 Expected 1-2 arguments, but got 0.
    40 | 
    41 | const UserContext = createContext(initialUserContext)
  > 42 | const UserContext1 = createContext()
       |                      ^
    43 | export const Provider = (
    44 |   <UserContext1.Provider value={{ state, dispatch: dispatchProxy }}>{children}</UserContext1.Provider>
    45 | )

```

but I agree that the doc says the initial value is optional when value is supplied

Even when I pass null, it has problem because of typescript's type checking

**Comment by hoangvvo** [comment]
This seems like a common Typescript error when I try to Google it. Unfortunately, I do not work in Typescript.

**Comment by maysam** [comment]
That's correct, I was following your tutorial only in typescript
