### ISSUE TITLE
Error when using with Mongoose

### ISSUE THREAD

**Issue by IRediTOTO** [hoangvvo/nextjs-mongodb-app#60]
Hello, thank you to made this. Can u please make an example for mongoose in nextjs ? I don't know why my codes not run. Hmm

**Comment by hoangvvo** [comment]
Hi @warcraft14115, I'm not planning on support Mongoose since it leads to degraded performance. 

I used to use Mongoose so if you post the log of your error I will try my best to help.

**Comment by IRediTOTO** [comment]
@hoangvvo  thank you for reply. Bạn người VN à? :s 
But almost docs on google are for mongoose, not mongodb native.
 I know mongoose slower than mongo native, but mongoose look like so popular.
OK i will learn mong native :|

**Comment by hoangvvo** [comment]
Hey @warcraft14115. You can still use mongoose since it requires only minimal changes in code. Again, feel free to post the error here, and I will try to point out the difference in mongoose. Otherwise, here is the doc for mongodb-native: http://mongodb.github.io/node-mongodb-native/3.6/api/

p/s: :point_right: VN :)

**Comment by IRediTOTO** [comment]
@hoangvvo  Thank you for made this, finally I understand your code :)) it's clean and beautifull. 
it maybe too complex for noob like me.

**Comment by IRediTOTO** [comment]
Hi, do you know what is this error?. First time I press to login button, i fetch first time status = 500 :| 
but click fetch one more time everything is ok. No error on console log server. So hard to find error with Nextjs, can't know where did I wrong. 
![image](https://user-images.githubusercontent.com/15695252/80910417-7ef7db80-8d59-11ea-8774-fb2bc49d6064.png)

**Comment by IRediTOTO** [comment]
hmm I fixed it, error from connect database, but why next didnt show it? Is there anyway to track error with next js?

**Comment by hoangvvo** [comment]
@warcraft14115 Next.js should log it. Do you have a reproduction (the error-ed one) for me to look at? It is difficult to figure it out without looking at it.

p/s: Lần sau bạn tag mình vào nha tại không mình sẽ không nhận đc noti cho closed issue.

**Comment by IRediTOTO** [comment]
@hoangvvo  ok thank you. Do you have any idea to upload large files to Vercel ? :s I want client upload then I will send to google drive. But they limited at 6MB :c this is sad. Or what paid host can I use (with easy deploy like Vercel :s )?

**Comment by deshario** [comment]
@IRediTOTO Can you share connection and using model examples with mongoose

**Comment by IRediTOTO** [comment]
> @IRediTOTO Can you share connection and using model examples with mongoose

Thank you but because this problem I change to use mongodb native. No mongoose anymore.
