### ISSUE TITLE
Can we make api/auth smoother when refresh page ? 

### ISSUE THREAD

**Issue by IRediTOTO** [hoangvvo/nextjs-mongodb-app#65]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/15695252/81795320-31882500-9536-11ea-8553-cb1eb3da7196.png)
Let's see this image
Is there anyway to make refresh page but  logged in user will not see the "Hello strenger"?  I mean check login from server, not fetch swr from client.

**Comment by IRediTOTO** [comment]
ops, image above not a gif, lets see this https://i.imgur.com/CvN6m50.gifv

**Comment by IRediTOTO** [comment]
I found it https://www.npmjs.com/package/next-connect#methodpattern-fns
But look like it will make loading slower right?
```
export async function getServerSideProps({ req, res }) {
   const handler=nextConnect();
   handler.use(middleware)
   handler.use(passport.initialize())

   await  handler.apply(req,res)
   console.log("user",req.user)
   return {
      props: {
         user:req.user,
      },
   };
}
```

**Comment by wortkotze** [comment]
i'm using https://www.npmjs.com/package/react-loading-skeleton to create a loading screen at the moment and we try to prefetch and have a service worker in place for caching.

if I use serverSideprops we are running into deployment issues on zeit after their new limits. so we are searching for new ways to deploy next completely to aws by our own

**Comment by IRediTOTO** [comment]
@wortkotze  You r right. I should do like that. Thanh you :)
