### ISSUE TITLE
New session id created for each request

### ISSUE THREAD

**Issue by edwardyh80** [hoangvvo/nextjs-mongodb-app#69]
**Describe the bug**
The session id keeps changing for each request if the user is not logged in.
Is this related to next-session package?

**To Reproduce**
Refreshing/navigating to another tab while keeping the Application tab of Developer's tool on should do the job.

**Expected behavior**
Probably the session id should be stable.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Latest stable

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hoangvvo** [comment]
I believe it is because of the `next-session` package. This is an expected behavior based on the way its code is written. The session id should not stay the same before a session is actually committed. Instead, would you prefer not to have a session id at all?

**Comment by edwardyh80** [comment]
That just sounds strange if you assign a session id to a guest that is not going to persist. Could you please give me some direction where to work on to change its behavior?

**Comment by hoangvvo** [comment]
In [session.ts](https://github.com/hoangvvo/next-session/blob/master/src/session.ts#L61), `shouldSetCookie` determines whether the cookie will be set. `saved` determines whether the session should be saved, only `true` if the session is actually committed. Check `saved = false` in `shouldSetCookie` should do.

**Comment by edwardyh80** [comment]
Okay thank you for you suggestion I am closing this.
