### ISSUE TITLE
Integration with sequelize

### ISSUE THREAD

**Issue by jamuna-r7o** [hoangvvo/nextjs-mongodb-app#71]
**Is your feature request related to a problem? Please describe.**
I managed to integrate PostgresQL with Sequelize instead of MongoDB, using your tutorial and the ones in the next.js examples.

**Describe the solution you'd like**
I could maybe add my version in my forked code. Would that be useful or not?

**Comment by hoangvvo** [comment]
Certainly @traderjosh. In a PR you can create a section above **Contributing** saying something like **Forks** and put a link there.

**Comment by jamuna-r7o** [comment]
@hoangvvo could you add the section for me please? 
It's here: https://github.com/traderjosh/nextjs-sequelize-app

I haven't deployed yet, and I still need to convert the token schema to a PostgreSQL table, along with a few other CRUD operations in the API routes.

Does Zeit / NOW allow for local databases? Because I won't be able to deploy because I'm not using a cloud database.

If you could also look at the conversions I made and let me know that'd be great

**Comment by hoangvvo** [comment]
Zeit does not allows a database unfortunately, you would need a 3rd party service to host the database and connect to it from Zeit

**Comment by jamuna-r7o** [comment]
Well the tables are being created with the relations, but this is being spammed in the console:

fetch.js:1 GET http://localhost:3000/api/user 500 (Internal Server Error)
fetch.js:1 GET http://localhost:3000/api/posts?from=&limit=10&by= 500 (Internal Server Error)

I have not even tried to login or register. Any idea what this means? I've just replaced the database and getters/setters, not anything else, so I don't know all your other code.

**Comment by jamuna-r7o** [comment]
This is the SQL being run constantly

Executing (default): SELECT "id", "name", "email", "password", "bio", "profilePicture", "emailVerified", "createdAt", "updatedAt" FROM "users" AS "users" WHERE "users"."sid" = 'sesion id here' LIMIT 1;

Not sure why it's querying the database with that. Maybe I'm missing something here, but shouldn't it be id and not sid?

**Comment by hoangvvo** [comment]
Can you provide some context to that? I'm not sure where that is. There is no `users.sid`. `sessionId` is stored in a different table.

**Comment by hoangvvo** [comment]
This is out of context with this repo. Feel free to reopen when you managed to work this out and I would be happy to add a link.
