### ISSUE TITLE
TypeError: mutate is not a function

### ISSUE THREAD

**Issue by jamuna-r7o** [hoangvvo/nextjs-mongodb-app#73]
**Describe the bug**
The mutate doesn't work in my version when I receive my user object from the database.

`    if (res.status === 200) {
      const userObj = await res.json();
      console.log(userObj);
      mutate(userObj);
    } else {
      setErrorMsg('Incorrect username or password. Try again!');
    }`

**Comment by hoangvvo** [comment]
I can't figure it out without a full repro and more context: what error you are seeing for example
