### ISSUE TITLE
null_ref

### ISSUE THREAD

**Issue by qnxdev** [hoangvvo/nextjs-mongodb-app#82]
null_ref

**Comment by hoangvvo** [comment]
What version of `next` are you using because I suspect you are using an older version? `nextjs-mongodb-app` only supports next.js v9.3 or later.

**Comment by qnxdev** [comment]
{
  "name": "halthis",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "connect-mongo": "^3.2.0",
    "dotenv": "^8.2.0",
    "mongodb": "^3.5.5",
    "next": "9.4.0",
    "next-connect": "^0.8.0",
    "next-session": "^3.2.3",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  }
}
 package.json

**Comment by hoangvvo** [comment]
This usually happens why you try to use `mongodb` on the client-side (probably by accident). Did you make any changes to the code?

**Comment by hoangvvo** [comment]
Also `req.db.collection('posts')` is incomplete. You probably want `req.db.collection('posts').find().toArray()` (find every document and transform them into array)

**Comment by qnxdev** [comment]
What do you mean by mongodb on client side?
So is it not possible to deploy this to github pages?
Is SSR required?

**Comment by qnxdev** [comment]
Right now I'm running this on my local PC  as localhost.

**Comment by qnxdev** [comment]
I'm running this on the localhost.
So how do I make this work on local machine?

Will this work as a SSG?

**Comment by hoangvvo** [comment]
Some pages will be SSR but most of them is SSG. You can first rename .env.example to .env to try it out. 

For the error, I would need to know what changes you made to the code if any because I don’t see that on my dev env

**Comment by qnxdev** [comment]
Hey thanks it's fixed now.
That .env worked
It actually my own project. I made it from scratch.
I just used your Database tech.

I think you should add this .env.example to.env process to the readme.md file.
Thanks
