### ISSUE TITLE
mongodb call too ussually

### ISSUE THREAD

**Issue by IRediTOTO** [hoangvvo/nextjs-mongodb-app#84]
**Describe the bug**
hi, i got this error from mongodb, i searched for it on google [https://jira.mongodb.org/browse/NODE-1868](https://jira.mongodb.org/browse/NODE-1868) problem because call mongodb too many time. 
```
the options [servers] is not supported
the options [caseTranslate] is not supported
the options [dbName] is not supported
the options [srvHost] is not supported
```
So I think to create a middleware called end.js. Is this the best way to fix this error ? Thank you

```
import { mongoClient } from "./database";

export default (req, res, next) => {
    mongoClient.close()
    console.log("close connect db")
    next()
};
```

**Comment by hoangvvo** [comment]
Are you in the dev environment? I think this is caused by React HMR.

**Comment by IRediTOTO** [comment]
> Are you in the dev environment? I think this is caused by React HMR.

yes, in local, I just checked on server, look like every thing work ok. "React HMR" ? You mean fetch api 2 times on client side ?

**Comment by hoangvvo** [comment]
Sorry, React HMR is [Hot Module Replacement](https://webpack.js.org/concepts/hot-module-replacement/). The server sorta "restarts" every time you make a change, so the mongodb connect function runs multiple times.
