### ISSUE TITLE
High number of connections on mongodb

### ISSUE THREAD

**Issue by esteban89** [hoangvvo/nextjs-mongodb-app#89]
Is it normal to have 30-50 connections to mongodb for just one user on production? (It's obviously higher on dev environment because of React HMR)
Number seems pretty high if I look forward to scale the number of users.

**Comment by hoangvvo** [comment]
Similar issue: https://github.com/hoangvvo/nextjs-mongodb-app/issues/87#issuecomment-663805716

> The error happens because we tries to `client.connect` many times (especially in dev environment with hot reload): https://jira.mongodb.org/browse/NODE-1868
> 
> However, in our code, we have already checked against it with `client.isConnected()` so that `client.connect` is called only once.
> 
> https://github.com/hoangvvo/nextjs-mongodb-app/blob/master/middlewares/database.js#L17
> 
> ...which, however, does not work with `useUnifiedTopology: true` @.@
> 
> https://jira.mongodb.org/browse/NODE-2234

Database never plays well with serverless in my experience...

**Comment by hoangvvo** [comment]
There is this alternative setup from vercel: https://vercel.com/guides/deploying-a-mongodb-powered-api-with-node-and-vercel

They make the assumption that `client` is always connected and only check if the database instance exists in cache and reuse it. I haven't tried that but it may work for you.

**Comment by BhaveshSGupta** [comment]
Should one open and close connection on each request and response? 
if we do that, then number of connections can be low or would there a issue here?

**Comment by StarAzure** [comment]
This is becoming a big issue in prod too. I am getting warning emails fro mongodb Atlas. Here is an example with just one user and one post, there are 238 connections. There is no hot reload in prod.

![image](https://user-images.githubusercontent.com/12852059/93274642-d3d84380-f788-11ea-9823-881b6c9d0110.png)

This will basically kill all our hard work which starts with this very useful repo. I hope someone can share a solution.

**Comment by hoangvvo** [comment]
@BhaveshSGupta We definitely can but there would be some perf issues since for the extra connect/disconnect.
@StarAzure This is a common issue for db in serverless environment. You can switch to non-serverless platform like Heroku. Another solution is to use [MongoDB Stitch](https://www.mongodb.com/collateral/mongodb-stitch-serverless-platform), which provides serverless db access.

**Comment by matthlavacka** [comment]
This is what I'm doing. Simply caching the database. (sorry it's using mongoose, not MongoClient)

```js
import mongoose from 'mongoose';

const uri = process.env.MONGODB_URI;
let cachedDb = null;

export default async function database(req, res, next) {
  try {
    if (cachedDb) {
      req.db = cachedDb;
      return next();
    }

    const connect = async () => mongoose.connect(uri, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useCreateIndex: true,
      useFindAndModify: false,
    });

    const connection = await connect();
    const { db } = connection?.connections?.[0];

    console.log(`===>  Succeeded in connecting to ${uri}`);

    cachedDb = db;
    req.db = db;

    return next();
  } catch (err) {
    console.log(`===>  Error connecting to ${uri}`);
    console.log(`Reason: ${err}`);
    throw new Error(err);
  }
}
```

**Comment by hoangvvo** [comment]
This is partly mitigated with https://github.com/hoangvvo/nextjs-mongodb-app/commit/5b2523e7fd588abd7f441e11f22f0e168b1c5147

**Comment by StarAzure** [comment]
@hoangvvo You nailed the fix and connections are much lower now. - Thanks. See it live - https://starazure.com
