### ISSUE TITLE
.

### ISSUE THREAD

**Issue by qnxdev** [hoangvvo/nextjs-mongodb-app#90]
.

**Comment by qnxdev** [comment]
?

**Comment by qnxdev** [comment]
@hoangvvo

**Comment by hoangvvo** [comment]
@qnxdev In `/api/user`, in `handler.patch`, there is a: 

```
const { name } = req.body
```

But you have set `bodyParser` to `false`, so `req.body` is `undefined`.

```
export const config = {
  api: {
    bodyParser: false,
  },
};
```

Did you mean to use something else there, like [`multer`](https://www.npmjs.com/package/multer)?

**Comment by qnxdev** [comment]
But when I set bodyParser: true, still req.body is undefined.

console shows this error, when form is submitted.
`API resolved without sending a response for /api/user, this may result in stalled requests.
(node:28345) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 9
    at ServerResponse.writeHead (_http_server.js:249:11)`
