### ISSUE TITLE
Invalid Url: undefined

### ISSUE THREAD

**Issue by consciousweb** [hoangvvo/nextjs-mongodb-app#91]
**Describe the bug**
New unaltered clone of repo produces the following cli error:

> TypeError [ERR_INVALID_URL]: Invalid URL: undefined
>     at onParseError (internal/url.js:243:9)
>     at new URL (internal/url.js:319:5)
>     at eval (webpack-internal:///./pages/api/user/index.js:32:5)
>     at Module../pages/api/user/index.js (/[redacted]/nextjs-mongodb-app/.next/server/pages/api/user.js:164:1)

**To Reproduce**
clone/npm i/ yarn dev

**Expected behavior**
no errors?

**Desktop (please complete the following information):**
 - OSX cli error

**Comment by hoangvvo** [comment]
Did you rename `.env.example` to `.env`? See https://github.com/hoangvvo/nextjs-mongodb-app#environmental-variables

**Comment by hoangvvo** [comment]
Close due to inactivity. Please reopen if needed.
