### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by iamfeek** [hoangvvo/nextjs-mongodb-app#98]
**Is your feature request related to a problem? Please describe.**
It isnt a problem, just a preference. 

Are you guys looking to include/migrate to Typescript?

That got me thinking, I can incrementally adopt Typescript in this project, right? 
Hmmm... Let me try that.

**Comment by hoangvvo** [comment]
In my opinion, I don't think it is a good idea to migrate this project to TypeScript because it is troublesome to non-TypeScript user.

**Comment by iamfeek** [comment]
Yeah, I can understand that sentiment. 

Actually, I have started coding off my own project that started as a template of this. 

And I added Typescript on it, but the current code is still in JS.

**Comment by poacher2k** [comment]
Just wanted to shoot in here that, while I fully agree that to a non-TypeScript user it would indeed be troublesome, it would be incredibly valuable to have a TS + next-connect + passport repository for reference.

I've yet to find any documentation on how to handle some of the roadblocks I've encountered thus far, like how to extend `NextApiRequest` the best way to include adding custom data to `req.session`, and even better - how to then specify the newly extended request to things like the `VerifyFunctionWithRequest`:

    passport.use(
      new LocalStrategy({ passReqToCallback: true },
        // TypeScript complains about req here being incompatible 
        async function (req: ExtendedRequest, username, password, done) { ... }
      )
    )

Anyhow, I really appreciate that you're working on this repo at all, and it has been very helpful so far. I just wished there were more resources on how to use `next-connect` (and next in general) with TS 😅
